APPIUM_SERVER: "http://127.0.0.1:4723/wd/hub"
PLATFORM: "iOS"
AUTOMATION_NAME: "XCUITest"
DEVICE_NAME: "iPhone 15"
NO_RESET: false
NEW_COMMAND_TIMEOUT: 120
# Si pruebas una app instalada, usa bundleId
BUNDLE_ID: "com.example.demo"